# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMovieDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('boxoffice', models.FloatField()),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProdCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capital', models.CharField(max_length=32)),
                ('location', models.TextField(max_length=128)),
                ('scope', models.TextField(default=None, max_length=512)),
                ('industry', models.TextField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerMovieDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.Duty')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.Movie')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.Producer')),
            ],
        ),
        migrations.AddField(
            model_name='companymovieduty',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.ProdCompany'),
        ),
        migrations.AddField(
            model_name='companymovieduty',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.Duty'),
        ),
        migrations.AddField(
            model_name='companymovieduty',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_collect.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='producermovieduty',
            unique_together=set([('producer', 'movie', 'duty')]),
        ),
        migrations.AlterUniqueTogether(
            name='companymovieduty',
            unique_together=set([('company', 'movie', 'duty')]),
        ),
    ]
