# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_collect', '0003_producermovieduty_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producermovieduty',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_collect.ProdCompany'),
        ),
    ]
